### ISSUE TITLE
Tracking FHIR conversion concerns

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#1770]
## Action Requested
Tracking FHIR conversion concerns so we know what to look for when we get more data

## Ongoing Checklist
**Lab Info:**
- [ ] Check whether any lab `Observations` use the `components` attribute other than those for lab organisms tables 
    - See PR #1762 -- Comments +378 to +380
- [ ] Check whether there are any examples of lab reports that have more than one "organisms" table per lab report. Currently, the code assumes we have a max of one organisms table per lab report. 
    - See PR #1762 -- using `.find` in `evaluateOrganismsReportData`
- [ ] Some lab component table fields are not displayed. 
    - For ex., in seed data `61f13d32-b25c-4fb6-998b-73de2dbf87f2`, the HTML eCR shows a `Value` for the `Final Report` component under `(ABNORMAL) Culture Bact Bld Adult (03/10/2022 10:00 AM CST)`. 
    - This does not show up in the eCR viewer because that value is only available in the HTML string, rather than the location we're performing FHIR conversion for that field.
    - Potential solution: If value is not available in FHIR, look up value in HTML string before displaying "No Data"?

## Acceptance Criteria
- All items in the checklist have been checked with new data

## Additional Information
