### ISSUE TITLE
SPIKE: Check FHIR bundles for reportable condition issues related to the conversion from ICD-9 to ICD-10

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2320]
## What needs to be done

For bundles where information isn't getting stamped by the TCR, cross-reference the triggerable codes from the RR information with the codes present in each of the FHIR bundle resources.
- Assuming you do find the OID for the ICD-9 system in the resources
    - [x] take those codes and figure out what the ICD-10 equivalent is, and 
    - [x] check to confirm whether or not it's present in the ERSD already

## Why it needs to be done

Currently, not all the relevant active problems and lab results are being pulled up in the Relevant Conditions section of the eCR Summary. After several informal spikes, we believe this may be due to the fact that. for the examples where it's not stamping the Conditions, the codes we have for the Conditions resources in the FHIR bundle are ICD 9, whereas the ERSD table used by the TCR service only has the ICD 10 equivalents. This spike can confirm this theory with other eCRs (including newer non-LAC examples).

## Timebox

_How much time should be dedicated to this spike?_

## To-do list

- [x] Current seed data (LAC)
- [x] New pilot seed data (TN)

## Additional context
- The OID `2.16.840.1.113883.6.103` indicates ICD-9 ([Link](https://phinvads.cdc.gov/vads/ViewCodeSystem.action?id=2.16.840.1.113883.6.103))
- Use the `/get-value-sets` endpoint to view the value set of clinical services associated with that condition.

**Comment by angelathe** [comment]
### Summary:

- Of the 13 LAC sample eCRs we have in the `ecr-viewer` container, **3** of them had issues. Of the 8 TDH sample eCRs we recently received, **1** of them we’re unsure about.
- **Summary of issues below:**
    1. ICD-9 codes are given, and the ICD-10 equivalent codes ARE included in the TCR value sets
        1. See LAC 1, Anthrax; LAC 3, Measles
    2. ICD-9 codes are given, but the ICD-10 equivalent codes ARE NOT included in the TCR value sets
        1. See LAC 1, COVID
    3. ICD-10 codes are given, but these codes ARE NOT included in our value sets.
        1. See LAC 2, COVID (2); TDH Hep B (2)

### LAC eCRs

1. `1c1393a3-2481-45a5-8610-392683aaef4a`
    - **Condition: Anthrax** (SNOMED condition code is `409498004)`
        - **Issue:** TCR did not stamp 1 condition
        - **Code in Condition resource:** `022.9` , an ICD-9 code.
        - **TCR value sets:** The TCR DOES include the ICD-10 equivalent in the value sets (`A22.9`).
            
            ```json
            "code": "022.9",
            "display": "Anthrax",
            "system": "urn:oid:2.16.840.1.113883.6.103"
            ```
            
    - **Condition: COVID** (SNOMED condition code is `840539006`)
        - **Issue:** TCR did not stamp 1 condition
        - **Code in Condition resource:** `079.89`, an ICD-9 code.
        - **TCR value sets**: When attempting to convert `079.89` to ICD-10, there are [ICD-10 equivalents codes](https://www.icd10data.com/Convert/079.89), but they don’t match up with the ICD-10 codes we have in the value sets.
            - Conversely, when converting the ICD-10 codes we do have in the value sets to ICD-9, I get the error: “**Not Found.** No conversion data could be found for the code specified. **Note**: CMS has not released an ICD-9-CM mapping for new ICD-10-CM/PCS codes. There is no data to convert ICD-10 codes added after 2018.”
            
            ```json
            "code": "079.89",
            "display": "Infection due to severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2)",
            "system": "urn:oid:2.16.840.1.113883.6.103"
            ```
            
2. `015ac0c5-9677-4596-b129-2c4d7eea30ab`
    - **Condition: COVID** (SNOMED condition code is `840539006`)
        - **Issue:** TCR did not stamp 2 conditions
        1. **Code in Condition resource**: `Z20.822`, an ICD-10 code ([Link](https://www.icd10data.com/ICD10CM/Codes/Z00-Z99/Z20-Z29/Z20-/Z20.822))
            - **TCR value sets:** This code is not found among the ICD-10 codes we have in the value sets.
                - Conversely, when converting the ICD-10 codes we do have in the value sets to ICD-9, I get the error: “**Not Found.** No conversion data could be found for the code specified. **Note**: CMS has not released an ICD-9-CM mapping for new ICD-10-CM/PCS codes. There is no data to convert ICD-10 codes added after 2018.”
            
            ```json
            "code": "Z20.822",
            "display": "Close exposure to COVID-19 virus",
            "system": "urn:oid:2.16.840.1.113883.6.90"
            ```
            
        2. **Code in Condition resource**: `B34.2`, an ICD-10 code ([Link](https://www.icd10data.com/ICD10CM/Codes/A00-B99/B25-B34/B34-/B34.2))
            - **TCR value sets:** This code is not found among the ICD-10 codes we have in the value sets.
            - However, this code IS a match from the conversion of `079.89` (ICD-9) to ICD-10. (from the #1, COVID example)
            - `B34.2` vs. the ICD-10 code in the value sets (`U07.1`) seem to exclude each other somehow? See: [Type 1 Excludes note](https://www.icd10data.com/ICD10CM/Codes/A00-B99/B25-B34/B34-/B34.2)
            
            ```json
            "code": "B34.2",
            "display": "Coronavirus infection",
            "system": "urn:oid:2.16.840.1.113883.6.90"
            ```
            
3. `0141cf19-3244-47cc-9255-5e263cec1151`
    - **Condition: Measles** (SNOMED condition code is `14189004)`
        - **Issue:** TCR did not stamp 1 condition
        - **Code in Condition resource:** `055.9` , an ICD-9 code.
        - **TCR value sets:** The TCR DOES include the ICD-10 equivalent in the value sets (`B05.9`).
            
            ```json
            "code": "055.9",
            "display": "Measles",
            "system": "urn:oid:2.16.840.1.113883.6.103"
            ```
            

### TDH eCR

- **Condition: Hepatitis B** (SNOMED condition code is `66071002`)
- **Issue**: TCR stamped 1/3 Condition resources
    - Not sure it triggered on all three, but feels like the TCR service should have identified all of them and stamped them?
- **Codes in Condition resource:** `R76.8` and `K73.9` , ICD-10 codes.
- **TCR value sets**: These codes are not found among the ICD-10 codes we have in the value sets.

```json
"code": "R76.8", // NOT stamped
"display": "Hepatitis B core antibody positive",
"system": "urn:oid:2.16.840.1.113883.6.90"

"code": "K73.9", // NOT stamped
"display": "Chronic hepatitis, unspecified",
"system": "urn:oid:2.16.840.1.113883.6.90"

"code": "B18.1", // WAS stamped
"display": "Chronic viral hepatitis B without delta-agent",
"system": "urn:oid:2.16.840.1.113883.6.90"
```

### Examples of eCRs that were correctly stamped:

`09f39529-69b8-4937-8e01-596b7e966d87` or `61f13d32-b25c-4fb6-998b-73de2dbf87f2`

- Codes for Plague/COVID are found in their respective value sets
- OID (ICD-10): `urn:oid:2.16.840.1.113883.6.90`
- Plague (`58750007`) → Code: `A20.2`
- COVID (`840539006`) → Code: `U07.1`

**Comment by angelathe** [comment]
@emmastephenson @gordonfarrell @sarahtress Included my brief summary above, followed by my notes on each case. Let me know if you think I should clean this up more before sending this along to the VIPER team!

**Comment by emmastephenson** [comment]
@angelathe this looks great! If you can send to VIPER would be much appreciated!
