### ISSUE TITLE
SPIKE: FHIR Converter issue(s) that cause eCRs to fail to run through the pipeline

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2454]
## What needs to be done

Figure out why several eCRs are failing to run through orchestration and the pipeline:

**1. TN sample eCRs (3):**
    - TN_sample eCR1: [Link](https://drive.google.com/drive/u/1/folders/1LVQnFhoNN55P1eiM7Il3el1tvvh31Bd-)
    - TN_sample eCR5: [Link](https://drive.google.com/drive/u/1/folders/1Xds0q9YUNx0M2aQGFghdUYimugaS2Sz2)
    - TN_sample eCR7: [Link](https://drive.google.com/drive/u/1/folders/1pKiummF2yCgKCRLGUMOdST_PG3EoUsgz)
**2. KY sample eCRs (2 - all)**
**3. Maine sample eCRs (3 - all)**
    - ME_sample eCR1: [Link](https://drive.google.com/drive/u/1/folders/15JG4YemSiMTPVOEC7bUUQbi_oSyoJ093)
    - ME_sample eCR2: [Link](https://drive.google.com/drive/u/1/folders/1gJnsf6KTaPOQdn-IaUZtXE6o6b-Eua9u)
    - ME_sample eCR3: [Link](https://drive.google.com/drive/u/1/folders/1ao_ysEWa1w87EIcQo9TJuheiDnZSCUjV)

See example failure messages below in **Additional Info**

## Why it needs to be done

_Describe the importance or impact of completing this task_

## Timebox

_How much time should be dedicated to this spike?_

## To-do list

- [x] Identify the issue(s) that cause eCRs listed above to fail to run through orchestration and the pipeline
- [ ] Create any necessary tickets to fix the issue(s) and add them as blockers to the following QA tickets:
    - [x] GitHub Issue: [QA Test TN eCR 1](https://github.com/CDCgov/phdi/issues/2352)
    - [x] GitHub Issue: [QA Test TN eCR 5](https://github.com/CDCgov/phdi/issues/2356)
    - [x] GitHub Issue: [QA Test TN eCR 7](https://github.com/CDCgov/phdi/issues/2358)
    - [x] GitHub Issue: [QA Test Maine eCR 1](https://github.com/CDCgov/phdi/issues/2358)
    - [x] GitHub Issue: [QA Test Maine eCR 2](https://github.com/CDCgov/phdi/issues/2358)
    - [x] GitHub Issue: [QA Test Maine eCR 3](https://github.com/CDCgov/phdi/issues/2358)

## Additional Info
**Ex. Failure message for TN sample eCR 1:**
```
Failed to convert TDH_1. Response: {"detail":"Service fhir_converter failed with error FHIR Converter request failed: 
{\"response\":{\"args\":\"dotnet /build/FHIR-Converter/output/Microsoft.Health.Fhir.Liquid.Converter.Tool.dll convert -- --
TemplateDirectory /build/FHIR-Converter/data/Templates/eCR --RootTemplate EICR --InputDataFile /tmp/ecr-input.txt --
OutputDataFile /tmp/output.json \",\"returncode\":255,\"stdout\":\"\",\"stderr\":\"Process failed: Error happened when 
rendering templates: Object reference not set to an instance of an object.\\n\",\"fhir_conversion_failed\":\"true\"}}"}
```

**Ex. Failure message for TN sample eCR 5:**
```
Failed to convert TDH_5. Response: {"detail":"Service fhir_converter failed with error FHIR Converter request failed: 
{\"response\":{\"args\":\"dotnet /build/FHIR-Converter/output/Microsoft.Health.Fhir.Liquid.Converter.Tool.dll convert -- --
TemplateDirectory /build/FHIR-Converter/data/Templates/eCR --RootTemplate EICR --InputDataFile /tmp/ecr-input.txt --
OutputDataFile /tmp/output.json \",\"returncode\":255,\"stdout\":\"\",\"stderr\":\"Process failed: Error happened when 
rendering templates: Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 
'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.\\n\",\"fhir_conversion_failed\":\"true\"}}"}
```

**Ex. Failure message for TN sample eCR 7:**
```
Failed to convert TDH_7. Response: {"detail":"Service fhir_converter failed with error FHIR Converter request failed: {\"response\":{\"args\":\"dotnet /build/FHIR-Converter/output/Microsoft.Health.Fhir.Liquid.Converter.Tool.dll convert -- --TemplateDirectory /build/FHIR-Converter/data/Templates/eCR --RootTemplate EICR --InputDataFile /tmp/ecr-input.txt --OutputDataFile /tmp/output.json \",\"returncode\":255,\"stdout\":\"\",\"stderr\":\"Process failed: Invalid JSON generated: line 73:2191 no viable alternative at input '\\\"entry\\\":[{\\\"fullUrl\\\":\\\"urn:uuid:1.2.840.114350.1.13.363.2.7.8.688883.861749262\\\",\\\"resource\\\":{\\\"resourceType\\\":\\\"Composition\\\",\\\"id\\\":\\\"1.2.840.114350.1.13.363.2.7.8.688883.861749262\\\",\\\"meta\\\":{\\\"profile\\\":[\\\"http://hl7.org/fhir/us/ecr/StructureDefinition/eicr-composition\\\"]},\\\"identifier\\\":[{\\\"use\\\":\\\"official\\\",\\\"type\\\":{\\\"coding\\\":[{\\\"code\\\":\\\"55751-2\\\",\\\"display\\\":\\\"Initial Public Health Case Report\\\",\\\"system\\\":\\\"http://loinc.org\\\",},],},\\\"value\\\":\\\"00000000-20f3-9085-0c68-e9e7bf945115\\\",\\\"assigner\\\":{\\\"display\\\":\\\"EPC\\\"},},],\\\"extension\\\":[{\\\"url\\\":\\\"http://hl7.org/fhir/StructureDefinition/composition-clinicaldocument-versionNumber\\\",\\\"valueString\\\":\\\"1\\\"},],\\\"status\\\":\\\"final\\\",\\\"type\\\":{\\\"coding\\\":[{\\\"code\\\":\\\"55751-2\\\",\\\"display\\\":\\\"Initial Public Health Case Report\\\",\\\"system\\\":\\\"http://loinc.org\\\",},],},\\\"date\\\":\\\"2024-07-30T14:34:08-05:00\\\",\\\"title\\\":\\\"Initial Public Health Case Report\\\",\\\"confidentiality\\\":\\\"N\\\",\\\"event\\\":[{\\\"period\\\":{\\\"start\\\":\\\"\\\",\\\"end\\\":\\\"\\\",},},],\\\"section\\\":[{\\\"id\\\":\\\"85fefb74-11d8-b393-7c60-f0c7bf2a88c8\\\",\\\"title\\\":\\\"Miscellaneous Notes\\\",\\\"text\\\":{\\\"status\\\":\\\"generated\\\",\\\"div\\\":\\\"<ul><li><caption>Discharge Summary - Georgette Rochelle Sevier, MD - Sat Jul 27, 2024 2:42 PM CDT</caption>Formatting of this note is different from the original. <br>7/27/2024, 2:43 PM Georgette Rochelle Sevier, MD, MDSUBMITTED BY:Pediatric Care will be at CCHS Orange Mound. Baby's Name is Idris The TardisHepatitis B vaccine DeclinedMother will make a follow up appointment for 2-4 days after discharge with CCHS , early for any problems.Discharge Follow Up: Normal newborn care, anticipatory guidance given, normal newborn handout to be given prior to discharge, discussed sleeping on back , discussed calling M.D. if rectal temperature > 100.4 F, if baby appears more jaundiced or appears dehydrated, or hearing screen and first hepatitis B vaccine prior to dischargeHomeDischarge Disposition:Discharge Cord Care: discussed cord careNewborn state screen done.Pending Labs and Tests at Discharge:Skin: Skin color, texture, turgor normal, no rashes or lesions.Neuro: Easily aroused; good symmetric tone and strength; positive root and suck; symmetric normal newborn reflexes.Extremities: Well-perfused, warm and dry.GU: Normal genitalia, FemaleHips: Negative Barlow, Ortolani, gluteal and thigh creases equal.Pulses: Strong equal femoral pulses, brisk capillary refill.Spine: Normal spine including sacrum.Abdomen: Soft, non-tender, no masses; umbilical stump clean and dry.Heart: Regular rate & rhythm, S1 S2, no murmurs, brachial and femoral pulses are equal.Chest: Lungs clear to auscultation, respirations unlabored, equal bilateral breath sounds, no tachypnea, no retractions, clavicles normal bilaterally.Neck: Supple, symmetrical, normal ROM.Throat: Lips, tongue, and mucosa are moist, pink and intact; palate intact.Nose: Clear, normal mucosa, patent nares.Ears: Well-positioned,well-formed pinnae, EAC's patent.Eyes:Sclerae white, pupils equal and reactive, red reflex normal bilaterally.Head: Sutures mobile, fontanelles normal size.General Appearance: Healthy-appearing, vigorous infant, strong cry, normal color and tone, perfused and hydrated, normal facies.Pulse 130 | Temp 98.2 °F (36.8 °C) | Resp 42 | Ht 18.5\\\"47'\\n.\\n\",\"fhir_conversion_failed\":\"true\"}}"}
```

**Comment by austin-hall-skylight** [comment]
@emmastephenson one of the issues we are seeing comes from mapping the reasons for visit to the extension on the composition resource. Previously we were getting text or a single table. Now we have to account for one or more items, each with one or more tables, and all of these tables have different columns. I'm concerned about breaking anything that might be working currently but do we want to try to account for all the possible reasons in the different tables and concatenate them into a comma delimited string for the extension section? 
Maine Patient 1 eicr:
<img width="611" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmVwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6173bfa3118255eefeb31222779729c0cb8fcadc/image.png" alt="image.png" />

<img width="1002" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnVwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cbf4175f883e889addb14d2eadd7c5d11d70630/image.png" alt="image.png" />


Maine Patient 2 eicr:
<img width="1021" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnFwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3eb1cf630d678746a33f8816cdd066f3f73431cc/image.png" alt="image.png" />

<img width="978" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnlwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--627f3e3480741b4742c5ef82281842f255585b8a/image.png" alt="image.png" />


Working example:
<img width="918" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjZwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--344253f07d4bec85cdfaa411793b6f0e3f4b39f0/image.png" alt="image.png" />

output:
<img width="1198" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNitwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37e67dded38820b7434254d9e8c98faf7677ab2f/image.png" alt="image.png" />

**Comment by emmastephenson** [comment]
@austin-hall-skylight good question! Normally I'd say that we should convert all possible data here. But much of this new "reason for visit" data actually looks like it's much more related to billing and insurance information, not the actual medical reason for visit. Given that, I don't know that it's super important to include it in the Viewer, esp. if those diagnoses/procedures are also present elsewhere in the record.

@sarahtress what do you think? Wondering if we need to include the fields highlighted in red in the Viewer if they're available.
![reason for visit](https://github.com/user-attachments/assets/29fe4e8c-9fa8-4e1f-b47c-2ed45b84a7fb)

**Comment by sarahtress** [comment]
> @austin-hall-skylight good question! Normally I'd say that we should convert all possible data here. But much of this new "reason for visit" data actually looks like it's much more related to billing and insurance information, not the actual medical reason for visit. Given that, I don't know that it's super important to include it in the Viewer, esp. if those diagnoses/procedures are also present elsewhere in the record.
> 
> @sarahtress what do you think? Wondering if we need to include the fields highlighted in red in the Viewer if they're available. ![reason for visit](https://private-user-images.githubusercontent.com/80282552/364155349-29fe4e8c-9fa8-4e1f-b47c-2ed45b84a7fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MDA4ODYsIm5iZiI6MTcyNTQwMDU4NiwicGF0aCI6Ii84MDI4MjU1Mi8zNjQxNTUzNDktMjlmZTRlOGMtOWZhOC00ZTFmLWI0N2MtMmVkNDViODRhN2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDIxNTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYzY3YzkyY2VhMDMzMjlkNTlhM2FlZDc0NTJkYTdjZmUzNGY3ZjVhZjM1ZjExYTRhMzY5MDI2OTlmMjVhZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fPRL0yYow4i3TP8Jxu5TJPsZBbog9uYDjy5MMPxDXPk)

I think I need to get more caught up with what exactly is going on here bc I'm a bit confused at what I'm seeing. I agree it looks billing related, but in an important way actually. we can chat about it more in standup tomorrow?
