### ISSUE TITLE
SPIKE: Folder monitoring for orchestration service

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#2551]
## What needs to be done

Investigate options for reading eCR data directly from a folder (without an API call to trigger the pipeline).
Anything from cron jobs to services like AWS Lambda could be considered here - the goal is to have an easy, low-lift way to start the pipeline when new data is dropped into a folder.

## Why it needs to be done

It's possible that jurisdictions on an older version of Rhapsody won't be able to send API requests to orchestration service to start the DIBBs pipeline. In these cases, Rhapsody would instead send a copy of the eCR/RR messages to a folder or S3 bucket, and our services would need to monitor this folder for incoming messages.

## Timebox

3 days

## To-do list

- [ ] Look into programmatic options for monitoring file systems
- [ ] Take notes on findings
- [ ] Present options to the development team
- [ ] Dev team makes a decision and epic/tickets are written accordingly

## Additional context

While we've used Azure Function Apps for this in the past, we're trying to avoid tying ourselves too closely to specific cloud tooling. This solution would ideally be able to run through a VM.

**Comment by lina-roth** [comment]
https://github.com/lina-roth/file-ingestion

**Comment by lina-roth** [comment]
<img width="810" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejhhQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfdb0b0e3b68cceb9b54887cb303fbd5779b6aa9/file%20ingestion%20app%20diagram.png" alt="file ingestion app diagram.png" />

**Comment by lina-roth** [comment]
Notes: https://docs.google.com/document/d/1uQXyIw-mme-pLkPzY1AQ6cBxxFKuJBAC9fLrRMdwKyM/edit?usp=sharing
