### ISSUE TITLE
SPIKE: Searching within eCR Viewer (Labs)

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#2600]
## What needs to be done

Determine if there's a way to page search within the eCR Viewer that will find data in collapsed sections (i.e., the labs that are automatically collapsed on open).

## Why it needs to be done

Searching is in the MVP designs for the eCR Viewer, but has not yet been implemented. Default page search functionality (cmd + f) is a partial solution, but it doesn't search through collapsed sections.

## Timebox

2 days

## To-do list

- [ ] Determine if searching through collapsed sections is possible
- [ ] Chat with Sarah/Emma about next steps
- [ ] Write any tickets required to implement search

**Comment by emmastephenson** [comment]
https://developer.chrome.com/docs/css-ui/hidden-until-found
