### ISSUE TITLE
SPIKE: Review QA issues related to missing fields/sections

### ISSUE THREAD

**Issue by angelathe** [CDCgov/phdi#2767]
## What needs to be done

In the [QA Issue Tracker spreadsheet](https://docs.google.com/spreadsheets/d/1ZmCbkKws1j9Xo7Kxj7Vo3ygu7GOjRKVCuWbWzD2Ph0Y/edit?gid=94191716#gid=94191716) (Playground sheet), there are a number of issues related to fields or sections that were displayed in the eICR HTML but that we either 1) do not currently convert to FHIR, and/or 2) do not have as designated fields/sections in the eCR Viewer.

For this spike, please review each of these issues to determine whether or not 1) these are valid field(s)/sections that we should be adding, 2) whether or not we are already converting them to FHIR, and 3) add tracking to these field(s)/sections that need to be added to the Viewer. See the to-do list below.

## Why it needs to be done

To ensure the eCR Viewer (accurately) displays all available information from the eCR, we need to address the QA cases where the HTML view of the eICR includes fields and sections that are not currently shown.

This spike is necessary to narrow down which are the missing fields/sections we should be adding to the Viewer, and to preeminently map the field(s)/sections that need FHIR conversion with where they live in the XML.

## Timebox

_How much time should be dedicated to this spike?_

## To-do list

For each row in the QA spreadsheet with the Issue Type as `Missing field` or `Misisng section`:
- [ ] Check that the missing field/section actually has data in the XML (i.e. if the example of the missing section does not have any available data, we won't count it)
- [ ] Check whether we already convert the missing field(s)/sections to FHIR or not. 
- [ ] If we DON'T already convert the field(s)/sections to FHIR: add to the [eCR Viewer Field Mapping spreadsheet](https://cdc.sharepoint.com/:x:/r/teams/OPHDST-IRD-DIBBs/Shared%20Documents/CDC%20DIBBs%20Project/Streamline%20Team/1%20-%20Pilot%20eCR%20Viewer%202024/5%20-%20Research%20%26%20Design/Design/eCR%20Viewer%20Field%20Mapping.xlsx?d=w80a53c04215840b6a7762dfc8b7267c9&csf=1&web=1&e=RIiBPb) 
    - [ ] where the information comes from in the XML
    - [ ] what field it should populate in the eCR Viewer
- [ ] If we do already convert the field(s)/sections to FHIR, then write a ticket to add the field(s)/sections to the eCR Viewer, and tag Ashton to add the Design Notes. 

## Additional context

Relevant resources:
- FHIR R4 spec

**Comment by angelathe** [comment]
Note: This is a continuation of #2599 to address all the QA issues that mention fields/sections that we do not currently have in the designs of the eCR Viewer.
