### ISSUE TITLE
SPIKE: display HTML tables for lab results

### ISSUE THREAD

**Issue by austin-hall-skylight** [CDCgov/phdi#2830]
## What needs to be done

Determine the feasibility of rendering the lab results HTML tables from eICR files in the viewer in place of how we currently display lab results.

## Why it needs to be done

Lab results come in a variety of formats from different EHR's. Aside from having to account for different column names, there are issues associating these tables and the data they contain with the correct observation. Displaying them as they are will give epis access to all of the data they contain and avoid conversion/display issues.

## Timebox

? days

## To-do list

- [ ] Determine if the HTML can be rendered and styled
- [ ] Chat with Ashton/Emma about next steps
- [ ] Write any tickets required to implement
