### ISSUE TITLE
[SPIKE] Understand eCR Viewer SQL DB

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#2944]
## 🚧 What needs to be done
We need to understand how the eCR viewer manages the SQL DB where normalized eCR data for the eCR library is stored.

## 🤔 Why it needs to be done
This needs to be done so that we can understand how to add a table to this DB to store eCR processing metadata necessary for the admin UI dashboard

## ⏰ Timebox
1 day

## 📝 To-do list

- [ ] How does the eCR Viewer manage its DB?
- [ ] How are the migrations run?
- [ ] If we want to add a table for the admin dashboard how do we do that?
- [ ] Where is there DDL?
- [ ]  How are migrations run?

**Comment by akasper** [comment]
Trigger code references are already in SQLite
