### ISSUE TITLE
SPIKE: Keycloak integration with Next Auth

### ISSUE THREAD

**Issue by austin-hall-skylight** [CDCgov/phdi#3064]
## What needs to be done

Test out authentication flow with Keycloak and Next Auth

## Why it needs to be done

Some of our partners are using Keycloak so we will need to make sure that we can use it for authentication.

## Timebox

_How much time should be dedicated to this spike?_

## To-do list

- [x] [Setup Keycloak to run locally](https://www.keycloak.org/getting-started/getting-started-docker)
- [x] [Create an openid-connect client in Keycloak](https://www.keycloak.org/docs/latest/server_admin/#_oidc_clients)
- [x] [Create a Keycloak provider in the eCR Viewer](https://next-auth.js.org/providers/keycloak)
- [x] Test out login in eCR Viewer

## Additional context

Query Connector has already integrated with Keycloak. Reach out to them if needed.

**Comment by lina-roth** [comment]
Code is pushed to branch `lr/keycloak` 

Middleware we are using for keycloak is just the default. The middleware we currently have doesn't play nicely with Keycloak. Started looking into strategy for creating middleware swapping for different auths and integrated vs non integrated vs both. Recommend adding a new spike for middleware swapping strategy. 

Closing this as Keycloak is displaying login screen with the ecr viewer.

**Comment by lina-roth** [comment]
Other notes: 

Had to add additional env vars for keycloak, you will need to modify these based on what the values are for your setup

`KEYCLOAK_ID=ecr-keycloak-client
KEYCLOAK_SECRET=K25cnXYtviWPCG12b7G1U0Ci6GVSp8mO
KEYCLOAK_ISSUER=http://localhost:9090/auth/realms/ecr-viewer

NEXTAUTH_SECRET="TMBV8xLIqEKvtWMyh0xmJoo0MWIhYQ4aEHwuBh3LohY=" # Added by `npx auth`. Read more: https://cli.authjs.dev
NEXTAUTH_URL=http://localhost:3000
`
