### ISSUE TITLE
SPIKE: Azure AD integration with Next Auth

### ISSUE THREAD

**Issue by austin-hall-skylight** [CDCgov/phdi#3065]
## What needs to be done

Test out authentication flow with Azure Active Directory and Next Auth

## Why it needs to be done

Some of our partners are using Azure Active AD so we will need to make sure that we can use it for authentication.

## Timebox

_How much time should be dedicated to this spike?_

## To-do list

- [x] [Work with DevOps to register the eCR Viewer in Azure AD](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app?tabs=certificate)
- [x] [Create a Azure AD provider in the eCR Viewer](https://next-auth.js.org/providers/azure-ad)
- [ ] Test out login in eCR Viewer

**Comment by lina-roth** [comment]
Result of this ticket is to have a branch with a POC of Azure AD working. 

Met with Alis to discuss configuring this in Azure, but unfortunately we are going to be blocked until Rin returns. So likely this ticket won't be able to make much progress until early January when everyone is back in office

**Comment by lina-roth** [comment]
Rin has added the app to azure. Unfortunately Im not a owner so Im unable to make modifications at this time - and I need to update the redirect url and add a client secret. I will work on the ecr viewer code portion, but most likely will be blocked until Rin is available again

**Comment by lina-roth** [comment]
Branch `lr/azure`

Added env vars 

> 
>  #Auth
> AZURE_AD_CLIENT_ID=9ff686a7-08ec-4c43-abc2-1efaa7b62426
> AZURE_AD_CLIENT_SECRET=
> AZURE_AD_TENANT_ID=28cf58df-efe8-4135-b2d1-f697ee74c00c
> 
> NEXTAUTH_SECRET="TMBV8xLIqEKvtWMyh0xmJoo0MWIhYQ4aEHwuBh3LohY=" # Added by `npx auth`. Read more: https://cli.authjs.dev
> NEXTAUTH_URL=http://localhost:3000

**Comment by lina-roth** [comment]
<img width="1407" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG1MQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77bb5feee144acb93bd5883ffddd6ec46b6b6d48/Screenshot%202025-01-22%20at%206.18.13%E2%80%AFPM.png" alt="Screenshot 2025-01-22 at 6.18.13 PM.png" />
